DOWNLOAD_VERSION: 0.8.1

ALERT_CLASS:
  all: 
  zh-TW: 
  en: 
  es: 
  fr: 
  nl: 
  
ALERT:
  all: 
  zh-TW: 
  en: 
  es: 
  fr: 
  nl: 

langsorder:
- id: zh-TW
- id: en
- id: es
- id: fr
- id: nl

langs:
  zh-TW: 繁體中文
  en: English
  es: Español
  fr: Français
  nl: Nederlands

section:
  index:
    en: 
    es: 
    fr: 
    nl:
  about:
    en: about
    es: acerca-de
    fr: a-propos
    nl: over-bitcoin
    zh-TW: about
  bitcoin-for-developers:
    en: bitcoin-for-developers
    es: bitcoin-para-desarrolladores
    fr: bitcoin-pour-developpeurs
    nl: bitcoin-voor-ontwikkelaars
    zh-TW: bitcoin-for-developers
  bitcoin-for-enthusiasts:
    en: bitcoin-for-enthusiasts
    es: bitcoin-para-entusiastas
    fr: bitcoin-pour-passionnes
    nl: bitcoin-voor-liefhebbers
    zh-TW: bitcoin-for-enthusiasts
  bitcoin-for-individuals:
    en: bitcoin-for-individuals
    es: bitcoin-para-personas
    fr: bitcoin-pour-particuliers
    nl: bitcoin-voor-particulieren
    zh-TW: bitcoin-for-individuals
  bitcoin-for-businesses:
    en: bitcoin-for-businesses
    es: bitcoin-para-empresas
    fr: bitcoin-pour-entreprises
    nl: bitcoin-voor-bedrijven
    zh-TW: bitcoin-for-businesses
  bitcoin-for-press:
    en: bitcoin-for-press
  choose-your-wallet:
    en: choose-your-wallet
    es: elige-tu-monedero
    fr: choisir-votre-porte-monnaie
    nl: kies-uw-portemonnee
    zh-TW: choose-your-wallet
  community:
    en: community
    es: comunidad
    fr: communaute
    nl: community
    zh-TW: community
  development:
    en: development
    es: desarrollo
    fr: developpement
    nl: ontwikkeling
    zh-TW: development
  download:
    en: download
    es: descargar
    fr: telecharger
    nl: download
    zh-TW: download
  foundation:
    en: foundation
    es: fundacion
    fr: fondation
    nl: stichting
    zh-TW: foundation
  how-it-works:
    en: how-it-works
    es: como-funciona
    fr: comment-ca-marche
    nl: hoe-het-werkt
    zh-TW: how-it-works
  resources:
    en: resources
    es: recursos
    fr: ressources
    nl: hulpmiddelen
    zh-TW: resources
  secure-your-wallet:
    en: secure-your-wallet
  support-bitcoin:
    en: support-bitcoin
    es: apoya-bitcoin
    fr: supporter-bitcoin
    nl: help-bitcoin
    zh-TW: support-bitcoin
  version-history:
    en: version-history
  vocabulary:
    en: vocabulary
    es: vocabulario
    fr: vocabulaire
    nl: woordenlijst
    zh-TW: vocabulary
  you-need-to-know:
    en: you-need-to-know
    es: debes-saber
    fr: vous-devez-savoir
    nl: wat-u-moet-weten
    zh-TW: you-need-to-know

vocabulary:
  address:
    en: address
    es: direccion
    fr: adresse
    nl: bitcoin-adres
  block-chain:
    en: blockchain
    es: cadena-de-bloques
    fr: chaine-de-bloc
    nl: blokketen
  block:
    en: block
    es: bloque
    fr: bloc
    nl: blok
  btc:
    en: btc
    es: btc
    fr: btc
    nl: btc
  confirmation:
    en: confirmation
    es: confirmacion
    fr: confirmation
    nl: bevestiging
  cryptography:
    en: cryptography
    es: criptografia
    fr: cryptographie
    nl: cryptografie
  double-spend:
    en: double-spend
    es: doble-gasto
    fr: double-depense
    nl: dubbele-uitgaven
  hash-rate:
    en: hash-rate
    es: velocidad-de-hash
    fr: taux-de-hash
    nl: hashsnelheid
  mining:
    en: mining
    es: mineria
    fr: minage
    nl: delven
  p2p:
    en: p2p
    es: p2p
    fr: p2p
    nl: p2p
  private-key:
    en: private-key
    es: llave-privada
    fr: cle-privee
    nl: geheime-sleutel
  signature:
    en: signature
    es: firma
    fr: signature
    nl: digitale-handtekening
  wallet:
    en: wallet
    es: monedero
    fr: porte-monnaie
    nl: portemonnee

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider
